---
title: "Resume"
---

One of my greatest experiences here at Appalachian State University was being given the privilege to work for orientation as a [Student Orientation Undergraduate Leader](https://workfororientation.appstate.edu/soul)(SOUL).  This organization has helped me develop and grow as a leader.  Here is a video that prides insight on what it means to work for orientation.

<figure align = "middle">
<iframe width="560" height="315" src="https://www.youtube.com/embed/pzh8AwstP-M" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
</figure>


During my time with orientation I was given the chance to help direct the program.  Therefore, I set my sights in improving the orientation experience from the inside.  This meant I developed more training and implemented a mentorship program.  I decided to do this based on research that supported mentorship and its positive influence on the growth of young professionals such as college students. 

* Below is a PDF of a powerpoint explaining the project I implemented as student director.  
* This Project took two semesters to plan and execute into the training of orientation.  

<iframe src="./SOUL_nile_director_project.pdf" width="100%" height="500px">

</iframe>
